### ISSUE TITLE
Not centering on internet explorer on windows 10

### ISSUE THREAD

**Issue by rafeafefaefeaa** [dolce/iziModal#82]
The modal is not centering on internet explorer windows 10. Not even this modal : http://izimodal.marcelodolce.com/#modal-custom

**Comment by dolce** [comment]
I'll check, thank you.

**Comment by dolce** [comment]
Fixed.
https://github.com/dolce/iziModal/releases/tag/v1.5.0

**Comment by rafeafefaefeaa** [comment]
The modal is still not centering on windows 10 IE with this options: window.modal.iziModal({
        title: 'Quick View',
        transitionIn: 'comingIn',
        transitionOut: 'comingOut',
        history: false,
        width: '60%',
        bottom: '10px',
        onClosed: function(){
            window.modal_content.html("")
        }
    });

You can test it on http://eufloria.ro on quick view of the product.

**Comment by dolce** [comment]
Now it has been fixed. Check out this release:
https://github.com/dolce/iziModal/releases/tag/v1.5.0
thanks.

**Comment by dolce** [comment]
Hello @rafeafefaefeaa, now it has been fixed. Check out this release:
https://github.com/dolce/iziModal/releases/tag/v1.5.0
Thanks.
